# Generated by Django 4.0.2 on 2022-02-24 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0001_initial'),
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bocasexpedicionmodel',
            name='boca_empleado',
            field=models.ManyToManyField(through='base.BocasEmpleadosModel', to='rrhh.EmpleadosModel'),
        ),
        migrations.AddField(
            model_name='bocasexpedicionmodel',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='base.sucursalesmodel'),
        ),
        migrations.AddField(
            model_name='bocasempleadosmodel',
            name='boca_expedicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.bocasexpedicionmodel'),
        ),
        migrations.AddField(
            model_name='bocasempleadosmodel',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.empleadosmodel'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='bocasexpedicionmodel',
            unique_together={('sucursal', 'nro_boca')},
        ),
    ]
