# Generated by Django 4.0.2 on 2022-02-25 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresasmodel',
            name='desc_corta',
        ),
        migrations.RemoveField(
            model_name='empresasmodel',
            name='desc_larga',
        ),
    ]
