# Generated by Django 4.0.2 on 2022-02-26 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_empresasmodel_desc_corta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numerossiguientesmodel',
            old_name='codigo_principal',
            new_name='codigo_1',
        ),
        migrations.RenameField(
            model_name='numerossiguientesmodel',
            old_name='codigo_secundario',
            new_name='codigo_2',
        ),
        migrations.RemoveField(
            model_name='bocasexpedicionmodel',
            name='desc_corta',
        ),
        migrations.RemoveField(
            model_name='bocasexpedicionmodel',
            name='desc_larga',
        ),
        migrations.RemoveField(
            model_name='bocasexpedicionmodel',
            name='nro_sucursal',
        ),
        migrations.RemoveField(
            model_name='numerossiguientesmodel',
            name='desc_corta',
        ),
        migrations.RemoveField(
            model_name='numerossiguientesmodel',
            name='desc_larga',
        ),
        migrations.AddField(
            model_name='numerossiguientesmodel',
            name='boca_expedicion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='base.bocasexpedicionmodel'),
        ),
    ]
