# Generated by Django 4.0.2 on 2022-02-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_codigo_principal_numerossiguientesmodel_codigo_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bocasempleadosmodel',
            name='default',
        ),
        migrations.AlterField(
            model_name='bocasempleadosmodel',
            name='estado',
            field=models.BooleanField(default=True, help_text='Indica cual es la sucursal/boca usadas en este momento'),
        ),
    ]
