# Generated by Django 4.0.2 on 2022-02-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_bocasempleadosmodel_default_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bocasempleadosmodel',
            constraint=models.UniqueConstraint(fields=('boca_expedicion', 'empleado'), name='bocasempleadosconst'),
        ),
    ]
