# Generated by Django 4.0.2 on 2022-02-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_bocasempleadosmodel_bocasempleadosconst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numerossiguientesmodel',
            name='codigo_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='numerossiguientesmodel',
            name='codigo_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
