# Generated by Django 4.0.2 on 2022-02-26 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_numerossiguientesmodel_codigo_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numerossiguientesmodel',
            name='boca_expedicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.bocasexpedicionmodel'),
        ),
    ]
