# Generated by Django 4.0.2 on 2022-02-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_numerossiguientesmodel_boca_expedicion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='numerossiguientesmodel',
            options={'verbose_name': 'Nro. Siguiente', 'verbose_name_plural': 'Nros. Siguientes'},
        ),
        migrations.AddConstraint(
            model_name='numerossiguientesmodel',
            constraint=models.UniqueConstraint(fields=('tip_documento', 'boca_expedicion'), name='nrosigbocaexpconst'),
        ),
    ]
