# Generated by Django 4.0.2 on 2022-02-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_numerossiguientesmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
            ],
        ),
        migrations.AlterUniqueTogether(
            name='bocasexpedicionmodel',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='bocasexpedicionmodel',
            constraint=models.UniqueConstraint(fields=('sucursal', 'nro_boca'), name='sucbocaconst'),
        ),
    ]
