# Generated by Django 4.0.2 on 2022-02-25 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturasmodel',
            name='quepasaaqui',
        ),
    ]
