# Generated by Django 4.0.2 on 2022-02-25 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_remove_facturasmodel_quepasaaqui'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='facturasmodel',
            managers=[
            ],
        ),
    ]
