# Generated by Django 4.0.2 on 2022-02-25 13:37

import aplicaciones.ventas.Precargas
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_facturasmodel_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturasmodel',
            name='cotizacion',
            field=models.PositiveIntegerField(default=aplicaciones.ventas.Precargas.FacturasPrecargas.cotizacion),
        ),
    ]
