# Generated by Django 4.0.2 on 2022-02-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_facturasmodel_cotizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturasmodel',
            name='cotizacion',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
