# Generated by Django 4.0.2 on 2022-03-01 14:16

import aplicaciones.ventas.Precargas
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_remove_conffinanzasmodel_moneda_predeterminada_and_more'),
        ('ventas', '0005_alter_facturasmodel_cotizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturasmodel',
            name='conf_cuotas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finanzas.confcuotasmodel', verbose_name='Cant. cuotas'),
        ),
        migrations.AlterField(
            model_name='facturasmodel',
            name='cotizacion',
            field=models.PositiveIntegerField(default=aplicaciones.ventas.Precargas.FacturasPrecargas.cotizacion),
        ),
        migrations.AlterField(
            model_name='facturasmodel',
            name='nro_documento',
            field=models.CharField(default='Cargar Nro Documento', max_length=100),
        ),
        migrations.AlterField(
            model_name='recibosventasmodel',
            name='nro_documento',
            field=models.CharField(default='Cargar Nro Documento', max_length=100),
        ),
    ]
