# Generated by Django 4.0.2 on 2022-03-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_alter_facturasmodel_conf_cuotas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturasmodel',
            name='nro_documento',
            field=models.CharField(default='Cargar Nro Documento', help_text='Los Nros de documentos legales deben tener el siguiente formato: 0010010000001', max_length=100),
        ),
        migrations.AlterField(
            model_name='recibosventasmodel',
            name='nro_documento',
            field=models.CharField(default='Cargar Nro Documento', help_text='Los Nros de documentos legales deben tener el siguiente formato: 0010010000001', max_length=100),
        ),
    ]
