# Generated by Django 4.0.2 on 2022-03-01 17:48

import aplicaciones.ventas.Precargas
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_movimientosarticulosmodel_nro_documento'),
        ('finanzas', '0004_remove_conffinanzasmodel_moneda_predeterminada_and_more'),
        ('shared_apps', '0001_initial'),
        ('ventas', '0007_alter_facturasmodel_nro_documento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarioCreacion', models.CharField(editable=False, max_length=20, verbose_name='base.UserProfile')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('usuarioModificacion', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='base.UserProfile')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('historico_cambios', models.JSONField(blank=True, default=dict, editable=False, null=True, verbose_name='Historico de actualizaciones del campo.')),
                ('estado', models.BooleanField(default=True)),
                ('borrado_logico', models.BooleanField(default=False, editable=False)),
                ('periodo', models.PositiveIntegerField(blank=True, null=True)),
                ('mes', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_documento', models.DateField(default=django.utils.timezone.now)),
                ('nro_documento', models.CharField(default='Cargar Nro Documento', help_text='Los Nros de documentos legales deben tener el siguiente formato: 0010010000001', max_length=100)),
                ('fecha_transaccion', models.DateField(default=django.utils.timezone.now)),
                ('observaciones', models.CharField(blank=True, max_length=1000, null=True)),
                ('cotizacion', models.PositiveIntegerField(default=aplicaciones.ventas.Precargas.FacturasPrecargas.cotizacion)),
                ('monto_mon_local', models.PositiveIntegerField(default=0)),
                ('ruc', models.CharField(default='', max_length=100)),
                ('razon_social', models.CharField(default='', max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.clientesmodel')),
                ('dep_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)sorig', to='stock.subdepositomodel')),
                ('moneda', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='shared_apps.monedamodel')),
                ('tip_documento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='shared_apps.tipdocumentodetmodel')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
            managers=[
                ('object_by_sucursal', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PedidosDetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarioCreacion', models.CharField(editable=False, max_length=20, verbose_name='base.UserProfile')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('usuarioModificacion', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='base.UserProfile')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('historico_cambios', models.JSONField(blank=True, default=dict, editable=False, null=True, verbose_name='Historico de actualizaciones del campo.')),
                ('estado', models.BooleanField(default=True)),
                ('borrado_logico', models.BooleanField(default=False, editable=False)),
                ('desc_larga', models.CharField(max_length=1000)),
                ('nro_item', models.IntegerField(default=0)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.PositiveIntegerField(default=0)),
                ('monto_mon_local', models.PositiveIntegerField(default=0)),
                ('monto_mon_ext', models.PositiveIntegerField(default=0)),
                ('Observaciones', models.CharField(blank=True, max_length=1000, null=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.articulosmodel')),
                ('impuesto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='finanzas.impuestosdetmodel')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.pedidosmodel')),
            ],
            options={
                'verbose_name': 'Detalle Pedido',
                'verbose_name_plural': 'Detalle de Pedidos',
            },
        ),
        migrations.AddConstraint(
            model_name='pedidosdetmodel',
            constraint=models.UniqueConstraint(fields=('pedido', 'nro_item'), name='peddetconstraint'),
        ),
    ]
