# Generated by Django 4.0.3 on 2022-03-03 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_pedidosremisionesmodel_remisionesdetmodel_pedido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemisionesFacturasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarioCreacion', models.CharField(editable=False, max_length=20, verbose_name='base.UserProfile')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('usuarioModificacion', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='base.UserProfile')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('historico_cambios', models.JSONField(blank=True, default=dict, editable=False, null=True, verbose_name='Historico de actualizaciones del campo.')),
                ('estado', models.BooleanField(default=True)),
                ('borrado_logico', models.BooleanField(default=False, editable=False)),
                ('cantidad', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='pedidosdetmodel',
            options={'verbose_name': 'Detalle de Pedido', 'verbose_name_plural': 'Detalle de Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='remisionesdetmodel',
            options={'verbose_name': 'Detalle de Remision', 'verbose_name_plural': 'Detalles de Remisiones'},
        ),
        migrations.AddField(
            model_name='facturasdetmodel',
            name='remision',
            field=models.ManyToManyField(related_name='remisionesfacturas', through='ventas.RemisionesFacturasModel', to='ventas.remisionesdetmodel'),
        ),
        migrations.AlterField(
            model_name='remisionesdetmodel',
            name='pedido',
            field=models.ManyToManyField(related_name='pedidosremisiones', through='ventas.PedidosRemisionesModel', to='ventas.pedidosdetmodel'),
        ),
        migrations.AddField(
            model_name='remisionesfacturasmodel',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.facturasdetmodel'),
        ),
        migrations.AddField(
            model_name='remisionesfacturasmodel',
            name='remision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.remisionesdetmodel'),
        ),
    ]
