# Generated by Django 4.0.3 on 2022-03-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_remisionesfacturasmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientesmodel',
            name='ruc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
