# Generated by Django 4.0.3 on 2022-03-25 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0013_clientesmodel_ruc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturasmodel',
            name='fecha_documento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Purchase Date(dd/mm/yyyy)'),
        ),
        migrations.AlterField(
            model_name='pedidosmodel',
            name='fecha_documento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Purchase Date(dd/mm/yyyy)'),
        ),
        migrations.AlterField(
            model_name='recibosventasmodel',
            name='fecha_documento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Purchase Date(dd/mm/yyyy)'),
        ),
        migrations.AlterField(
            model_name='remisionesmodel',
            name='fecha_documento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Purchase Date(dd/mm/yyyy)'),
        ),
    ]
