# Generated by Django 4.0.5 on 2022-07-01 00:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_acumuladorarticulos_fecha_documento_and_more'),
        ('ventas', '0014_alter_facturasmodel_fecha_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturasmodel',
            name='dep_origen',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)sorig', to='stock.subdepositomodel', verbose_name='Deposito'),
        ),
        migrations.AlterField(
            model_name='facturasmodel',
            name='fecha_documento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='facturasmodel',
            name='monto_mon_local',
            field=models.PositiveIntegerField(default=0, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='facturasmodel',
            name='saldo_mon_local',
            field=models.PositiveIntegerField(default=0, verbose_name='Saldo'),
        ),
        migrations.AlterField(
            model_name='pedidosmodel',
            name='dep_origen',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)sorig', to='stock.subdepositomodel', verbose_name='Deposito'),
        ),
        migrations.AlterField(
            model_name='pedidosmodel',
            name='fecha_documento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='recibosventasmodel',
            name='fecha_documento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='remisionesmodel',
            name='dep_origen',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)sorig', to='stock.subdepositomodel', verbose_name='Deposito'),
        ),
        migrations.AlterField(
            model_name='remisionesmodel',
            name='fecha_documento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
