# Generated by Django 4.0.5 on 2022-07-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0015_alter_facturasmodel_dep_origen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibosventasmodel',
            name='observaciones',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
