# Generated by Django 4.0.5 on 2022-07-13 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0017_clientessucursalesmodel_celular_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientessucursalesmodel',
            old_name='fec_ingreso',
            new_name='fecha_ingreso',
        ),
    ]
