# Generated by Django 4.0.2 on 2022-02-24 21:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared_apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondCompVentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarioCreacion', models.CharField(editable=False, max_length=20, verbose_name='base.UserProfile')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('usuarioModificacion', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='base.UserProfile')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('historico_cambios', models.JSONField(blank=True, default=dict, editable=False, null=True, verbose_name='Historico de actualizaciones del campo.')),
                ('estado', models.BooleanField(default=True)),
                ('borrado_logico', models.BooleanField(default=False, editable=False)),
                ('desc_corta', models.CharField(blank=True, max_length=100, null=True)),
                ('desc_larga', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Condicion compra/venta',
                'verbose_name_plural': 'Condiciones de compra/venta',
            },
        ),
        migrations.CreateModel(
            name='ConfCuotasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarioCreacion', models.CharField(editable=False, max_length=20, verbose_name='base.UserProfile')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('usuarioModificacion', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='base.UserProfile')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('historico_cambios', models.JSONField(blank=True, default=dict, editable=False, null=True, verbose_name='Historico de actualizaciones del campo.')),
                ('estado', models.BooleanField(default=True)),
                ('borrado_logico', models.BooleanField(default=False, editable=False)),
                ('desc_corta', models.CharField(blank=True, max_length=100, null=True)),
                ('desc_larga', models.CharField(max_length=1000)),
                ('cant_cuotas', models.PositiveIntegerField(default=0)),
                ('cant_dias_primera_cuota', models.PositiveIntegerField(default=3)),
                ('pago_anticipado', models.BooleanField(default=False)),
                ('venc_fecha_fija', models.PositiveIntegerField(blank=True, default=0, help_text='Dia del mes de cada cuota', null=True, verbose_name='Dia del Vencimiento Fijo')),
                ('pri_cuota_mes_factura', models.BooleanField(default=True, help_text='Si la primera cuota se cuenta en el mismo mes de la factura. Ej. Si una factura tienefecha 25 y fecha fija = True y esta configurada al 26 de cada mes entonces laprimera cuota se daria recien el siguiente mes', verbose_name='Primera cuota en mes de factura')),
            ],
            options={
                'verbose_name': 'configuracion de cuota',
                'verbose_name_plural': 'configuraciones de cuotas',
            },
        ),
        migrations.CreateModel(
            name='ImpuestosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarioCreacion', models.CharField(editable=False, max_length=20, verbose_name='base.UserProfile')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('usuarioModificacion', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='base.UserProfile')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('historico_cambios', models.JSONField(blank=True, default=dict, editable=False, null=True, verbose_name='Historico de actualizaciones del campo.')),
                ('estado', models.BooleanField(default=True)),
                ('borrado_logico', models.BooleanField(default=False, editable=False)),
                ('desc_corta', models.CharField(blank=True, max_length=100, null=True)),
                ('desc_larga', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Impuesto',
                'verbose_name_plural': 'Impuestos',
            },
        ),
        migrations.CreateModel(
            name='ImpuestosDetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarioCreacion', models.CharField(editable=False, max_length=20, verbose_name='base.UserProfile')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('usuarioModificacion', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='base.UserProfile')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('historico_cambios', models.JSONField(blank=True, default=dict, editable=False, null=True, verbose_name='Historico de actualizaciones del campo.')),
                ('estado', models.BooleanField(default=True)),
                ('borrado_logico', models.BooleanField(default=False, editable=False)),
                ('desc_corta', models.CharField(blank=True, max_length=100, null=True)),
                ('desc_larga', models.CharField(max_length=1000)),
                ('nro_item', models.IntegerField(default=0)),
                ('formula', models.CharField(blank=True, max_length=100, null=True)),
                ('valor1', models.PositiveIntegerField(default=0)),
                ('valor2', models.PositiveIntegerField(default=0)),
                ('valor3', models.PositiveIntegerField(default=0)),
                ('valor4', models.PositiveIntegerField(default=0)),
                ('valor5', models.PositiveIntegerField(default=0)),
                ('impuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.impuestosmodel')),
            ],
            options={
                'verbose_name': 'detalle impuesto',
                'verbose_name_plural': 'detalles impuestos',
            },
        ),
        migrations.CreateModel(
            name='CotizacionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarioCreacion', models.CharField(editable=False, max_length=20, verbose_name='base.UserProfile')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('usuarioModificacion', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='base.UserProfile')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('historico_cambios', models.JSONField(blank=True, default=dict, editable=False, null=True, verbose_name='Historico de actualizaciones del campo.')),
                ('estado', models.BooleanField(default=True)),
                ('borrado_logico', models.BooleanField(default=False, editable=False)),
                ('desc_corta', models.CharField(blank=True, max_length=100, null=True)),
                ('desc_larga', models.CharField(max_length=1000)),
                ('compra', models.DecimalField(decimal_places=0, max_digits=10)),
                ('venta', models.DecimalField(decimal_places=0, max_digits=10)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shared_apps.monedamodel')),
            ],
            options={
                'verbose_name': 'Cotizacion',
                'verbose_name_plural': 'Cotizaciones',
            },
        ),
        migrations.CreateModel(
            name='ConfFinanzasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarioCreacion', models.CharField(editable=False, max_length=20, verbose_name='base.UserProfile')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('usuarioModificacion', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='base.UserProfile')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('historico_cambios', models.JSONField(blank=True, default=dict, editable=False, null=True, verbose_name='Historico de actualizaciones del campo.')),
                ('estado', models.BooleanField(default=True)),
                ('borrado_logico', models.BooleanField(default=False, editable=False)),
                ('conf_comp_venta', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='finanzas.condcompventmodel')),
                ('moneda_predeterminada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shared_apps.monedamodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='impuestosdetmodel',
            constraint=models.UniqueConstraint(fields=('impuesto', 'nro_item'), name='impdetconstraint'),
        ),
    ]
