# Generated by Django 4.0.2 on 2022-02-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacionmodel',
            name='desc_corta',
        ),
        migrations.RemoveField(
            model_name='cotizacionmodel',
            name='desc_larga',
        ),
    ]
