# Generated by Django 4.0.2 on 2022-02-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_remove_cotizacionmodel_desc_corta_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cotizacionmodel',
            constraint=models.UniqueConstraint(fields=('moneda', 'fecha'), name='cotimonfecsconst'),
        ),
    ]
