# Generated by Django 4.0.2 on 2022-02-25 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_apps', '0001_initial'),
        ('finanzas', '0003_cotizacionmodel_cotimonfecsconst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conffinanzasmodel',
            name='moneda_predeterminada',
        ),
        migrations.AddField(
            model_name='conffinanzasmodel',
            name='moneda_local',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='moneda_local', to='shared_apps.monedamodel', verbose_name='Moneda Local'),
        ),
        migrations.AddField(
            model_name='conffinanzasmodel',
            name='moneda_secundaria',
            field=models.ForeignKey(default=2, help_text='Es la moneda con la cual es estaremos generando los reportes internacionales', on_delete=django.db.models.deletion.PROTECT, related_name='moneda_secundaria', to='shared_apps.monedamodel', verbose_name='Moneda secundaria'),
        ),
    ]
