# Generated by Django 4.0.3 on 2022-03-03 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_apps', '0002_clasificacionesmenusmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulossistemamodel',
            name='orden_visualizacion',
        ),
        migrations.RenameModel(
            old_name='SubModulosSistemaModel',
            new_name='SubMenusSistemasModel',
        ),
        migrations.CreateModel(
            name='MenusSistemaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarioCreacion', models.CharField(editable=False, max_length=20, verbose_name='base.UserProfile')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('usuarioModificacion', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='base.UserProfile')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('historico_cambios', models.JSONField(blank=True, default=dict, editable=False, null=True, verbose_name='Historico de actualizaciones del campo.')),
                ('estado', models.BooleanField(default=True)),
                ('borrado_logico', models.BooleanField(default=False, editable=False)),
                ('desc_corta', models.CharField(blank=True, max_length=100, null=True)),
                ('desc_larga', models.CharField(max_length=1000)),
                ('orden_visualizacion', models.PositiveIntegerField(default=0)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shared_apps.modulossistemamodel')),
            ],
            options={
                'verbose_name': 'modulo SAAS',
                'verbose_name_plural': 'modulos SAAS',
            },
        ),
        migrations.AlterField(
            model_name='submenussistemasmodel',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shared_apps.menussistemamodel'),
        ),
    ]
