# Generated by Django 4.0.3 on 2022-03-03 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_apps', '0003_remove_modulossistemamodel_orden_visualizacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menussistemamodel',
            options={'verbose_name': 'Menu SAAS', 'verbose_name_plural': 'Menus SAAS'},
        ),
    ]
