# Generated by Django 4.0.3 on 2022-03-04 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_apps', '0004_alter_menussistemamodel_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submenussistemasmodel',
            old_name='modulo',
            new_name='menu',
        ),
    ]
