# Generated by Django 4.0.3 on 2022-03-12 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_apps', '0005_rename_modulo_submenussistemasmodel_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clasificacionesmenusmodel',
            options={'verbose_name': 'Clasificacion', 'verbose_name_plural': 'Clasificaciones'},
        ),
    ]
