# Generated by Django 4.0.2 on 2022-03-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientosarticulosmodel',
            name='nro_documento',
            field=models.CharField(default='Cargar Nro Documento', max_length=100),
        ),
    ]
