# Generated by Django 4.0.2 on 2022-03-01 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_movimientosarticulosmodel_nro_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientosarticulosmodel',
            name='dep_destino',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)sdest', to='stock.subdepositomodel'),
        ),
        migrations.AlterField(
            model_name='movimientosarticulosmodel',
            name='dep_origen',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)sorig', to='stock.subdepositomodel'),
        ),
    ]
