# Generated by Django 4.0.3 on 2022-03-25 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_movimientosarticulosmodel_dep_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acumuladorarticulos',
            name='fecha_documento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Purchase Date(dd/mm/yyyy)'),
        ),
        migrations.AlterField(
            model_name='movimientosarticulosmodel',
            name='fecha_documento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Purchase Date(dd/mm/yyyy)'),
        ),
    ]
