# Generated by Django 4.0.2 on 2022-02-26 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpleadosModelProxy',
            fields=[
                ('empleadosmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rrhh.empleadosmodel')),
            ],
            options={
                'verbose_name': 'Empleados',
            },
            bases=('rrhh.empleadosmodel',),
        ),
    ]
