# Generated by Django 4.0.2 on 2022-02-26 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0002_empleadosmodelproxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmpleadosModelProxy',
        ),
        migrations.CreateModel(
            name='EmpleadosModelProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Empleados',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rrhh.empleadosmodel',),
        ),
    ]
