# Generated by Django 4.0.2 on 2022-02-26 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0003_delete_empleadosmodelproxy_empleadosmodelproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleadosmodelproxy',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
    ]
