# Generated by Django 4.0.2 on 2022-02-26 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0004_alter_empleadosmodelproxy_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleadosmodel',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='empleadosmodelproxy',
            options={'verbose_name': 'EmpleadoP', 'verbose_name_plural': 'EmpleadosP'},
        ),
        migrations.RenameField(
            model_name='empleadosmodel',
            old_name='fec_egreso',
            new_name='fecha_egreso',
        ),
        migrations.RenameField(
            model_name='empleadosmodel',
            old_name='fec_ingreso',
            new_name='fecha_ingreso',
        ),
    ]
