# Generated by Django 4.0.2 on 2022-02-26 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0005_alter_empleadosmodel_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmpleadosModelProxy',
        ),
        migrations.CreateModel(
            name='EmpleadosProxy',
            fields=[
            ],
            options={
                'verbose_name': 'EmpleadoP',
                'verbose_name_plural': 'EmpleadosP',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rrhh.empleadosmodel',),
        ),
    ]
