# Generated by Django 4.0.2 on 2022-02-26 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0006_delete_empleadosmodelproxy_empleadosproxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmpleadosProxy',
        ),
        migrations.CreateModel(
            name='EmpleadosBocasProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Empleado/boca',
                'verbose_name_plural': 'Empleados/Bocas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rrhh.empleadosmodel',),
        ),
    ]
