# Generated by Django 4.0.5 on 2022-07-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_userprofile_managers'),
        ('rrhh', '0008_alter_empleadosmodel_empleado_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleadosmodel',
            name='empleado_sucursal',
            field=models.ManyToManyField(through='rrhh.EmpleadosSucursalesModel', to='base.sucursalesmodel'),
        ),
    ]
