# Generated by Django 4.0.5 on 2022-07-02 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0009_alter_empleadosmodel_empleado_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarioCreacion', models.CharField(editable=False, max_length=20, verbose_name='base.UserProfile')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('usuarioModificacion', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='base.UserProfile')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('historico_cambios', models.JSONField(blank=True, default=dict, editable=False, null=True, verbose_name='Historico de actualizaciones del campo.')),
                ('estado', models.BooleanField(default=True)),
                ('borrado_logico', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmpleadosBeneficiosModel',
            fields=[
                ('usuarioCreacion', models.CharField(editable=False, max_length=20, verbose_name='base.UserProfile')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('usuarioModificacion', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='base.UserProfile')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('historico_cambios', models.JSONField(blank=True, default=dict, editable=False, null=True, verbose_name='Historico de actualizaciones del campo.')),
                ('estado', models.BooleanField(default=True)),
                ('borrado_logico', models.BooleanField(default=False, editable=False)),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('beneficio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.beneficiosmodel')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.empleadosmodel')),
            ],
            options={
                'verbose_name': 'Empleado Beneficio',
                'verbose_name_plural': 'Empleados Beneficios',
            },
        ),
        migrations.AddField(
            model_name='empleadosmodel',
            name='beneficios',
            field=models.ManyToManyField(through='rrhh.EmpleadosBeneficiosModel', to='rrhh.beneficiosmodel'),
        ),
    ]
