# Generated by Django 4.0.5 on 2022-07-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0010_beneficiosmodel_empleadosbeneficiosmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiosmodel',
            name='desc_corta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beneficiosmodel',
            name='desc_larga',
            field=models.CharField(default='Hola mundo', max_length=1000),
            preserve_default=False,
        ),
    ]
