# Generated by Django 4.0.6 on 2022-07-13 23:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0012_alter_empleadosbeneficiosmodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleadosmodel',
            name='fecha_ingreso_ips',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='empleadosmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Laboral'),
        ),
    ]
