# Generated by Django 4.0.6 on 2022-07-14 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0013_empleadosmodel_fecha_ingreso_ips_and_more'),
        ('tesoreria', '0002_alter_entidadesfinancierasmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidadesfinancierasmodel',
            name='persona',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='rrhh.personasmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entidadesfinancierasmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='entidadesfinancierasmodel',
            name='oficial_cuentas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entfin_oficialcuentas', to='rrhh.personasmodel', verbose_name='Oficial Ctas.'),
        ),
    ]
