# Generated by Django 4.0.6 on 2022-07-14 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0013_empleadosmodel_fecha_ingreso_ips_and_more'),
        ('tesoreria', '0004_alter_entidadesfinancierasmodel_oficial_cuentas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadesfinancierasmodel',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='rrhh.personasmodel'),
        ),
    ]
